### ISSUE TITLE
The link to preprocessed dataset of DeEx in tuta is broken

### ISSUE THREAD

**Issue by AriKing11** [microsoft/TUTA_table_understanding#9]
The link I refer to is as follows:
https://drive.google.com/file/d/1xJkq2DQciWvndhgm0aHZXMqzIWSan9z9/view?usp=sharing

**Comment by gaojiasheng241** [comment]
This site can‘t be opened

**Comment by AriKing11** [comment]
> This site can‘t be opened


yep, so i hope that the author will re-update this resource
